-- Update Artworks Image URLs
-- Generated by upload-cloudinary.js
-- Run this in PostgreSQL after successful upload

-- Impressionisme Category
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469867/artconnect/artworks/impressionisme/imp1.jpg' WHERE title = 'Sunrise Reflection';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469869/artconnect/artworks/impressionisme/imp2.jpg' WHERE title = 'Garden Dreams';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469871/artconnect/artworks/impressionisme/imp3.jpg' WHERE title = 'Water Lilies Echo';

-- Abstract Category
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469873/artconnect/artworks/abstrakt/abs1.jpg' WHERE title = 'Cosmic Harmony';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469874/artconnect/artworks/abstrakt/abs2.jpg' WHERE title = 'Flowing Emotions';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469876/artconnect/artworks/abstrakt/abs3.jpg' WHERE title = 'Color Symphony';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469877/artconnect/artworks/abstrakt/abs4.jpg' WHERE title = 'Abstract Waves';

-- Expressionism Category
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469879/artconnect/artworks/ekspressionisme/eks1.jpg' WHERE title = 'The Scream Reimagined';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469881/artconnect/artworks/ekspressionisme/eks2.jpg' WHERE title = 'Emotional Landscape';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469882/artconnect/artworks/ekspressionisme/eks3.jpg' WHERE title = 'Inner Turmoil';

-- Street Art Category
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469887/artconnect/artworks/street-art/st1.jpg' WHERE title = 'Urban Revolution';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469888/artconnect/artworks/street-art/st2.jpg' WHERE title = 'City Walls Speak';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469890/artconnect/artworks/street-art/st3.jpg' WHERE title = 'Graffiti Dreams';

-- Visual Art / Digital Art Category
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469892/artconnect/artworks/visual-art/vis1.png' WHERE title = 'Digital Sunrise';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469895/artconnect/artworks/visual-art/vis2.png' WHERE title = 'Cyber Garden';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469899/artconnect/artworks/visual-art/vis3.png' WHERE title = 'Neon Nights';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469902/artconnect/artworks/visual-art/vis4.png' WHERE title = 'Pixel Paradise';

-- Others / Mixed Media
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469903/artconnect/artworks/others/monalisa.jpg' WHERE title = 'Enigmatic Smile';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469905/artconnect/artworks/others/matahari.jpg' WHERE title = 'Solar Radiance';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469907/artconnect/artworks/others/pelangi.jpg' WHERE title = 'Rainbow Spectrum';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469909/artconnect/artworks/others/mukabanyak.jpg' WHERE title = 'Many Faces';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469911/artconnect/artworks/others/canvascircle.jpg' WHERE title = 'Circular Canvas';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469913/artconnect/artworks/others/bunga.jpg' WHERE title = 'Floral Symphony';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469915/artconnect/artworks/others/sketsa1.jpg' WHERE title = 'Sketch Study';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469917/artconnect/artworks/others/tumpukan.jpg' WHERE title = 'Layered Reality';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469920/artconnect/artworks/others/look.png' WHERE title = 'Watching Eyes';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469922/artconnect/artworks/others/layer1.png' WHERE title = 'Layer One';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469924/artconnect/artworks/others/layer2.png' WHERE title = 'Layer Two';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469925/artconnect/artworks/others/artwork1.png' WHERE title = 'Contemporary Vision';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469928/artconnect/artworks/others/artwork2.png' WHERE title = 'Modern Expression';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469931/artconnect/artworks/others/artwork3.png' WHERE title = 'Artistic Flow';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469932/artconnect/artworks/others/artwork4.png' WHERE title = 'Creative Burst';

-- Photography Category (Mount Bromo series)
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469935/artconnect/artworks/others/br1.jpg' WHERE title = 'Mount Bromo Sunrise';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469936/artconnect/artworks/others/br2.jpg' WHERE title = 'Bromo Crater';
UPDATE artworks SET image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469938/artconnect/artworks/others/br3.jpg' WHERE title = 'Volcanic Majesty';

-- Update Galleries Cover Images:
UPDATE galleries SET cover_image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469956/artconnect/galleries/pameran1.jpg' WHERE name = 'Modern Abstract Collection';
UPDATE galleries SET cover_image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469958/artconnect/galleries/pameran2.jpg' WHERE name = 'Digital Dreams';
UPDATE galleries SET cover_image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469959/artconnect/galleries/pameran3.jpg' WHERE name = 'Sculptural Visions';
UPDATE galleries SET cover_image_url = 'https://res.cloudinary.com/dqoit6ruy/image/upload/v1765469961/artconnect/galleries/gallerysee.png' WHERE name = 'Nature Through Lens';
